version: "3.4"

services:
  server:
    image: deephaven-examples/podcast-aggregation:latest
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - api-cache:/cache
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}

  web:
    image: ghcr.io/deephaven/web:${VERSION:-latest}
    expose:
      - '80'
    volumes:
      - ./data:/data
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
    environment:
      - BACKEND_ADDR=server:8080
    depends_on:
      - server
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:${VERSION:-latest}
    depends_on:
      - web
      - grpc-proxy
      - server
    ports:
      - "10000:10000"
      
volumes:
    web-tmp:
    api-cache:
